### ISSUE TITLE
go get themis does not work

### ISSUE THREAD

**Issue by i-walker** [cossacklabs/themis#431]
go get github.com/cossacklabs/themis/gothemis/session
go: finding github.com/cossacklabs/themis/gothemis/session latest
go: finding github.com/cossacklabs/themis/gothemis latest
go: finding github.com/cossacklabs/themis latest
# github.com/cossacklabs/themis/gothemis/keys
../../pkg/mod/github.com/cossacklabs/themis@v0.0.0-20190321165223-ef592257ccce/gothemis/keys/keypair.go:10:10: fatal error: 'themis/secure_keygen.h' file not found
#include <themis/secure_keygen.h>

**Comment by ilammy** [comment]
Hi @i-walker,

Thank you for letting us know! :(

The issue you're seeing seems to be caused by version mismatch between GoThemis and core Themis library. By default, `go get` fetches the latest Go code from master branch, where we made some refactoring and small fixes. Unfortuntely, they are not compatible with the current stable version of Themis core (0.10.0).

We are going to release the next stable version of the core library next week. This should resolve the issue after you upgrade to 0.11.0.

As a temporary workaround I'd recommend you to _downgrade_ your copy of GoThemis. You can switch to the `0.10.0` version the following way:

```
cd ${GOPATH:-~/go}/src/github.com/cossacklabs/themis
git checkout 0.10.0
```

**Important:** do not use `go get -u` after that, please avoid upgrading your copy of GoThemis for a while.

(There is also an alternative approach: [build the latest Themis version from source,][1] but that's a much more involved process.)

We're very sorry for the inconvenience. Dealing with dependency issues and versioning of Go packages is so cumbersome :/ We will update installation docs, too!

[1]: https://github.com/cossacklabs/themis/wiki/Go-HowTo#installing-themis

**Comment by i-walker** [comment]
No Problem thank you. 
Do you know if there is a Gitter/ Slack Channel for questions? 
I am still getting used to working with themis.

**Comment by vixentael** [comment]
@i-walker we closed a Gitter chat, because we just didn't have time to check it :(

You're welcome to ask questions here in Github Issue or just ping us at our dev team email: dev@cossacklabs.com
